zuul:
  #Service will be mapped under the /api URI
  prefix: /api
  routes:
    hello-client:
      path: /zuulc/**
      serviceId: GET-BOOKINGS
   
       
    hello-producer:
      path: /zuuld/**
      serviceId: GET-BOOKING
      
    hello-client-add:
      path: /zuule/**
      serviceId: AUTH-SERVER  

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
  instance:
    hostname: localhost

server:
  port: 8073

spring:
  application:
    name: zuul-service

# Increase the Hystrix timeout to 60s (for all)
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000